/**
 * 
 */
package com.software.group2.controllers;

import java.math.BigInteger;
import java.util.Optional;

/**
 * @author Austin
 *
 */
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.software.group2.entities.Admin;
import com.software.group2.repos.AdminRepo;



@Controller    // This means that this class is a Controller
@RequestMapping(path="/admin") // This means URL's start with /software (after Application path)
public class AdminCont {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private AdminRepo adminRepository;

	
	@PostMapping(path="/add", consumes= {"application/json"} ) // Map ONLY POST Requests
	public @ResponseBody String addNewAdmin (@RequestBody Admin n) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		adminRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/getall")
	public @ResponseBody Iterable<Admin> getAllAdmins() {
		// This returns a JSON or XML with the users
		return adminRepository.findAll();
	}
	
	@GetMapping(path="/getone/user")
	public @ResponseBody Optional<Admin> getOneAdmin(@RequestParam String adminUserName) {
		// This returns a JSON or XML with the admin
		return adminRepository.findByAdminUsername(adminUserName);
	}
	
	@GetMapping(path="/approveInst")
	public @ResponseBody int approveInst(@RequestParam Integer id,@RequestParam Integer approval) {
		// This returns a JSON or XML with the admin
		return adminRepository.updateApproveInst(id, approval);
	}
	
	@GetMapping(path="/checkone/user")
	public @ResponseBody boolean checkOneAdminUser(@RequestParam String adminUserName) {
		// This returns a JSON or XML with the admin
		 BigInteger ret = adminRepository.checkByAdminUserName(adminUserName);
		 int result = ret.intValue();
		 System.out.println(result);
		 if(result == 1) {
			 return true;
		 }
		 return false;
		 
	}
}

