/**
 * 
 */
package com.software.group2.controllers;

import java.util.Optional;

/**
 * @author Austin
 *
 */
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.software.group2.entities.Institution;
import com.software.group2.repos.InstitutionRepo;



@Controller    // This means that this class is a Controller
@RequestMapping(path="/inst") // This means URL's start with /software (after Application path)
public class InstitutionCont {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private InstitutionRepo instRepository;

	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewInst (@RequestParam String name) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		Institution n = new Institution();
		n.setInstitutionName(name);
		instRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/getall")
	public @ResponseBody Iterable<Institution> getAllAdmins() {
		// This returns a JSON or XML with the users
		return instRepository.findAll();
	}
	
	@GetMapping(path="/getone")
	public @ResponseBody Optional<Institution> getOneAdmin(@RequestParam Integer id) {
		// This returns a JSON or XML with the admin
		return instRepository.findById(id);
	}
}

